- name: Apply Nginx template
  template:
    src: files/nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: Restart Nginx
  service: 
    name: nginx
    state: restarted
  
