---
- name: Donwload source packages installer
  shell: "curl -sL https://deb.nodesource.com/setup_18.x -o /tmp/nodesetup.sh"

- name: Execute installer
  shell: "bash /tmp/nodesetup.sh"

- name: Install support packages
  apt: 
    name: "{{item}}"
  with_items:
  - gcc 
  - g++ 
  - make

- name: Install nodejs
  apt: 
    name: "nodejs"